# List of plugins
set -g @plugin 'tmux-plugins/tpm'

# Custom key bindings
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Status bar configuration
set -g status-bg black
set -g status-fg white
set -g status-left " #[fg=green]#H #[fg=white] "
set -g status-right "  #[fg=blue]%Y-%m-%d "

# Mouse support
set -g mouse on

# Window renaming
setw -g automatic-rename on

# Better pane navigation
bind-key Up select-pane -U
bind-key Down select-pane -D
bind-key Left select-pane -L
bind-key Right select-pane -R

# Session saving and restoration
set -g @resurrect-dir "~/.tmux/resurrect"  # Specify the directory for tmux-resurrect
run-shell "~/.tmux/plugins/tpm/tpm"         # Load Tmux Plugin Manager
