# Set terminal overrides for better compatibility
set-option -sa terminal-overrides ",xterm*:Tc"
set-option -g default-terminal "tmux-256color"

# Customize status bar
set-option -g status-bg colour234
set-option -g status-fg white
set-window-option -g window-status-current-style fg=yellow2
set-option -g status-left " "
set -g status-right "Session: #S "
set-option -g window-status-current-format " #I:[#W]"

# Reload the tmux configuration without restarting
bind r source-file ~/.config/tmux/tmux.conf \; display-message " Config reloaded..."

# Bind key 'f' to run tmux-sessionizer script
bind-key -r f run-shell "tmux neww ~/.local/scripts/tmux-sessionizer"

# Enable mouse support
set -g mouse on

# Set escape time to 10 milliseconds
set-option -sg escape-time 10

# Enable focus events
set-option -g focus-events on

# Prevent automatic detachment on pane/window destroy
set -g detach-on-destroy off

# Set default terminal
set -g default-terminal "${TERM}"

# Enable clipboard integration
set -g set-clipboard on

# Set status bar position at the top
set -g status-position top

# Customize key bindings
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Kill window with Alt+&
unbind &
bind X kill-window

# Start windows and panes at 1 instead of 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

# Set vi-mode in copy mode
set-window-option -g mode-keys vi

# Keybindings for copy mode in vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Bind keys for splitting windows
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
