[main]
font=JetBrainsMono Nerd Font Mono:size=11
dpi-aware=yes

[scrollback]
lines=5000

[mouse]
hide-when-typing=yes

[tweak]
font-monospace-warn=no

# DARK THEME ("Theme 1")
[colors]
background=1a1b26
foreground=cfc9c2
regular0=1a1b26
regular1=fd8493
regular2=a6d588
regular3=f0b86a
regular4=b2c7fd
regular5=d5befc
regular6=68def1
regular7=cfc9c2
bright0=565f89
bright1=ffb3ba
bright2=c2e5ad
bright3=f8d29a
bright4=d1deff
bright5=e5d5ff
bright6=a1edfb
bright7=f9f4ee

# LIGHT THEME ("Theme 2")
[colors2]
background=faf8f5
foreground=373b41
regular0=d1d1d1
regular1=b03038
regular2=388e3c
regular3=825300
regular4=0065a7
regular5=7437cc
regular6=006789
regular7=373b41
bright0=8e95b3
bright1=8e2027
bright2=1a3618
bright3=633f00
bright4=004a7a
bright5=58299c
bright6=004e68
bright7=1a1b26
