return {
  'm4xshen/smartcolumn.nvim',
  event = { 'BufReadPost', 'BufNewFile' },
  opts = {
    disabled_filetypes = {
      'NvimTree',
      'gitcommit',
      'lua',
      'json',
      'netrw',
      'lazy',
      'html',
      'mason',
      'help',
      'text',
      'markdown',
      'log',
      'man',
      'diff',
      'swp',
      'tmp',
      'info',
      'checkhealth',
      'lspinfo',
      'zsh',
      'gitconfig',
    },
  },
}
