return {
  'nvim-treesitter/nvim-treesitter',
  build = ':TSUpdateSync',
  cmd = 'TSUpdateSync',
  event = 'BufNewFile',
  main = 'nvim-treesitter.configs',
  opts = {
    ensure_installed = {
      'bash',
      'c',
      'diff',
      'html',
      'query',
      'lua',
      'luadoc',
      'markdown',
      'markdown_inline',
      'vim',
      'vimdoc',
    },
    sync_install = true,
    auto_install = true,
    highlight = { enable = true },
    indent = { enable = true },
  },
}
