local g = vim.g
g.mapleader = " "
g.maplocalleader = " "
g.loaded_perl_provider = 0
g.loaded_ruby_provider = 0
g.loaded_node_provider = 0
g.loaded_python_provider = 0
g.loaded_python3_provider = 0
local o = vim.o
o.background = require("iton.util").set_bg()
o.signcolumn = require("iton.util").signcol_size
o.scrolloff = math.floor(vim.api.nvim_win_get_height(0) / 2)
o.winborder = "rounded"
o.inccommand = "split"
o.colorcolumn = "80"
o.timeoutlen = 400
o.textwidth = 80
o.tabstop = 4
o.shiftwidth = 4
o.showmode = false
o.linebreak = true
o.undofile = true
o.ignorecase = true
o.smartcase = true
