#!/usr/bin/env bash

set -e

# Update dependencies
sudo apt update

# Define list of packages to install
packages=("unzip" "make" "tmux" "zsh" "fzf" "sed" "ripgrep" "xclip" "gcc" "python3.10-venv")

# Install all packages
sudo apt install -y "${packages[@]}"

echo "Tools installed successfully..."

# Upgrade packages
sudo apt upgrade -y

# Install oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended --keep-zshrc

# Clone zsh plugins
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

# Install nvm and install latest available version
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash

echo "Zsh configured successfully."

# Install Neovim
echo "Installing Neovim..."
curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
sudo rm -rf /opt/nvim-linux64
sudo mkdir -p /opt/nvim-linux64
sudo chmod a+rX /opt/nvim-linux64
sudo tar -C /opt -xzf nvim-linux64.tar.gz
# Make it available in /usr/local/bin, distro installs to /usr/bin
sudo ln -sf /opt/nvim-linux64/bin/nvim /usr/local/bin/
echo "Neovim installed successfully."
/opt/nvim-linux64/bin/nvim --version
rm nvim-linux64.tar.gz

# Create directories
mkdir -p "$HOME/personal/neovim_dev"
mkdir -p "$HOME/work"
mkdir -p "$HOME/sandbox"

echo -e "\n---------------------------"
echo -e "Main installation finished!\n"
echo -e "[IMPORTANT]\n"
echo -e "Run 'chsh -s \$(which zsh)' before rebooting\n"
echo -e "Reboot system and open link in\n"
echo -e "'Post Install' of ~/README.md"
