#!/usr/bin/env bash

# Update package list
sudo apt update -y || {
    echo "Error: Failed to update package list."
    exit 1
}

# Install essential dependencies
sudo apt install -y cat curl tar gzip unzip wget cmake python3 make zip || {
    echo "Error: Failed to install essential dependencies."
    exit 1
}

# Install Git, Vim, Tmux, Zsh, and other tools
sudo apt install -y vim tmux zsh fzf sed ripgrep xclip gcc || {
    echo "Error: Installation of Vim, Tmux, Zsh, fzf, sed, ripgrep, xclip failed."
    exit 1
}

# Output success message
echo "Tools (Vim, Tmux, Zsh, fzf, sed, ripgrep, xclip) installed successfully..."

# Install oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

# Validate zsh config
cat ~/.zshrc
echo "Is this the correct zsh config? (y/n) "
read -r response

if [[ "$response" =~ ^[Yy]$ ]]; then
    echo "Continuing Install..."
else
    echo "Copying contents of .zshrc.pre-oh-my-zsh to .zshrc..."
    echo "Contents of previous .zshrc in .zshrc-from-install"
    mv ~/.zshrc ~/.zshrc-from-install
    mv ~/.zshrc.pre-oh-my-zsh ~/.zshrc
    echo "Finished."
fi

# Upgrade packages
sudo apt upgrade -y

# Make zsh default shell and run zsh
chsh -s "$(which zsh)" || {
    echo "Error: Failed to set zsh as the default shell."
    exit 1
}
# Install latest version of starship shell prompt
curl -sS https://starship.rs/install.sh | sh
zsh || {
    echo "Error: Failed to start zsh."
    exit 1
}
echo "Zsh configured successfully."
echo ""
echo "Running 'update' alias..."
echo "--------------------------------"
echo ""

# Install lazygit
echo "Installing LazyGit..."
LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": "v\K[^"]*')
curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
tar xf lazygit.tar.gz lazygit
sudo install lazygit /usr/local/bin
echo "Current LazyGit version:"
lazygit --version
rm lazygit.tar.gz
echo "--------------------------------"
echo ""

# Install Neovim
echo "Installing Neovim..."
curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
sudo rm -rf /opt/nvim
sudo tar -C /opt -xzf nvim-linux64.tar.gz
echo "--------------------------------"
echo "Current Neovim version:"
/opt/nvim-linux64/bin/nvim --version
rm nvim-linux64.tar.gz
echo "--------------------------------"
echo ""

# Start tmux
tmux || {
        echo "Error: Failed to start tmux."
        exit 1
    }
    echo "Tmux started successfully."
    echo "Main Installation Finished!"
    echo "May need to install further dependencies and/or reboot."
