#!/usr/bin/env bash

sudo apt install -y unzip make vim tmux zsh fzf sed ripgrep xclip gcc || {
    echo "Error: Installation of Vim, Tmux, Zsh, fzf, sed, ripgrep, xclip failed."
    exit 1
}

echo "Tools (Vim, Tmux, Zsh, fzf, sed, ripgrep, xclip) installed successfully..."

sudo apt upgrade -y

tmux || {
        echo "Error: Failed to start tmux."
        exit 1
    }
    echo "Tmux started successfully."

# Install oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended --keep-zshrc
# NOTE: if the above works delete the zsh config validation below

# Validate zsh config
tail -1 ~/.zshrc
echo "Is this the correct zsh config? (y/n) "
read -r response

if [[ "$response" =~ ^[Yy]$ ]]; then
    echo "Continuing Install..."
else
    echo "Copying contents of .zshrc.pre-oh-my-zsh to .zshrc..."
    echo "Contents of previous .zshrc in .zshrc-from-install"
    mv ~/.zshrc ~/.zshrc-from-install
    mv ~/.zshrc.pre-oh-my-zsh ~/.zshrc
    echo "Finished."
fi

# Install latest version of starship shell prompt
curl -sS https://starship.rs/install.sh | sh
zsh || {
    echo "Error: Failed to start zsh."
    exit 1
}
echo "Zsh configured successfully."
echo "--------------------------------"
echo ""

echo "Installing Neovim..."
curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
sudo rm -rf /opt/nvim
sudo tar -C /opt -xzf nvim-linux64.tar.gz
echo "--------------------------------"
echo "Current Neovim version:"
/opt/nvim-linux64/bin/nvim --version
rm nvim-linux64.tar.gz
nvim --headless "+Lazy! sync" +qa # Runs neovim in headless and makes sure plugins updated
echo "--------------------------------"
echo ""

echo "Main Installation Finished!"
echo "May need to install further dependencies, Nerd Font, and/or reboot."
