#!/usr/bin/env bash

# Query current state via gsettings (or you could use dbus-send)
CURRENT_THEME=$(gsettings get org.gnome.desktop.interface color-scheme | tr -d "'")

if [ "$CURRENT_THEME" = "prefer-dark" ]; then
    NEW_SCHEME="prefer-light"
    GTK_THEME="Adwaita"
    NVIM_BG="light"
    pkill -USR2 foot
else
    NEW_SCHEME="prefer-dark"
    GTK_THEME="Adwaita-dark"
    NVIM_BG="dark"
    pkill -USR1 foot
fi

# 1. Update GTK/GNOME settings
gsettings set org.gnome.desktop.interface color-scheme "$NEW_SCHEME"
gsettings set org.gnome.desktop.interface gtk-theme "$GTK_THEME"

# 2. Update XDG Portal
dbus-send --session --type=method_call --dest=org.freedesktop.impl.portal.Desktop.Gtk \
    /org/freedesktop/portal/desktop \
    org.freedesktop.impl.portal.Settings.ReadAll \
    array:string:"org.freedesktop.appearance"

# 3. Update the Cache
echo "$NVIM_BG" > "${XDG_CACHE_HOME:-$HOME/.cache}/nvim_theme"

# 4. Broadcast to Neovim
SOCKET_DIR="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"

for socket in "$SOCKET_DIR"/nvim.*.0; do
    if [ -S "$socket" ]; then
        timeout 0.1s nvim --server "$socket" --remote-send "<C-\><C-n>:set background=$NVIM_BG<CR>" > /dev/null 2>&1 &
    fi
done

wait
