#!/usr/bin/env bash

sudo cp $HOME/.local/scripts/new_machine_setup/arch_update/arch_auto_update.service /etc/systemd/system/arch_auto_update.service
sudo cp $HOME/.local/scripts/new_machine_setup/arch_update/arch_auto_update.timer /etc/systemd/system/arch_auto_update.timer

sudo systemctl daemon-reload

sudo systemctl enable arch_auto_update.service
sudo systemctl start arch_auto_update.service
sudo systemctl enable arch_auto_update.timer
sudo systemctl start arch_auto_update.timer



