#!/usr/bin/env bash
if command -v pacman >/dev/null 2>&1; then # Arch
	sudo pacman -S github-cli
elif command -v apt >/dev/null 2>&1; then # Ubuntu
	echo "Configuring APT repository for GitHub CLI..."
	(type -p wget >/dev/null || sudo apt install wget -y) \
		&& sudo mkdir -p -m 755 /etc/apt/keyrings \
		&& wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
		&& sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
		&& echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
	sudo apt install -y gh
else
	sudo dnf install -y gh
fi
