#!/usr/bin/env bash

echo "Installing Latest Go Version..."

LATEST_GO_VERSION=$(curl -s https://go.dev/dl/ | grep -oP 'go\d+\.\d+\.\d+\.linux-amd64\.tar\.gz' | head -n 1)

sudo rm -rf /usr/local/go
sudo tar -C /usr/local -xzf $LATEST_GO_VERSION

rm $LATEST_GO_VERSION
