#!/usr/bin/env bash
mkdir -p "$HOME/Code/personal"
mkdir -p "$HOME/Code/neovim_dev"
mkdir -p "$HOME/Code/work"
mkdir -p "$HOME/Code/sandbox"
curl -sSL https://raw.githubusercontent.com/iton0/hkup-cli/main/scripts/install | sh
cd "$HOME/Code/personal"
git clone --depth 1 --filter=blob:none git@github.com:iton0/iton0.github.io.git my-website
cd "$HOME/Code/personal/my-website"
git pull --set-upstream origin main
cd "$HOME"
git clone --depth 1 --filter=blob:none git@github.com:ErikReider/SwayAudioIdleInhibit.git
cd SwayAudioIdleInhibit
meson build
ninja -C build
sudo meson install -C build
cd "$HOME"
rm -rf SwayAudioIdleInhibit
