#!/usr/bin/env bash

if command -v pacman >/dev/null 2>&1; then # Arch
	sudo pacman -S wezterm ttf-nerd-fonts-symbols-mono
else
	# Configure system to use APT repo for WezTerm
	echo "Configuring APT repository for WezTerm..."
	curl -fsSL https://apt.fury.io/wez/gpg.key | sudo gpg --yes --dearmor -o /etc/apt/keyrings/wezterm-fury.gpg
	echo 'deb [signed-by=/etc/apt/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *' | sudo tee /etc/apt/sources.list.d/wezterm.list

	sudo apt update

	sudo apt install -y wezterm

	# Set WezTerm as default terminal
	echo "Setting WezTerm as default terminal..."
	sudo ln -sf /usr/bin/wezterm /etc/alternatives/x-terminal-emulator
fi
