#!/usr/bin/env bash
if command -v pacman >/dev/null 2>&1; then # Arch
	sudo pacman -S wezterm ttf-nerd-fonts-symbols-mono
elif command -v apt >/dev/null 2>&1; then # Arch
	# Configure system to use APT repo for WezTerm
	echo "Configuring APT repository for WezTerm..."
	curl -fsSL https://apt.fury.io/wez/gpg.key | sudo gpg --yes --dearmor -o /etc/apt/keyrings/wezterm-fury.gpg
	echo 'deb [signed-by=/etc/apt/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *' | sudo tee /etc/apt/sources.list.d/wezterm.list
	sudo apt update
	sudo apt install -y wezterm
else
	sudo dnf install -y https://github.com/wez/wezterm/releases/download/20240203-110809-5046fc22/wezterm-20240203_110809_5046fc22-1.fedora39.x86_64.rpm
fi
