#!/usr/bin/env bash
if command -v apt >/dev/null 2>&1; then # Ubuntu
	# Configure system to use APT repo for WezTerm
	echo "Configuring APT repository for WezTerm..."
	curl -fsSL https://apt.fury.io/wez/gpg.key | sudo gpg --yes --dearmor -o /etc/apt/keyrings/wezterm-fury.gpg
	echo 'deb [signed-by=/etc/apt/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *' | sudo tee /etc/apt/sources.list.d/wezterm.list
	sudo apt update
	sudo apt install -y wezterm
else # Fedora
    sudo dnf copr enable wezfurlong/wezterm-nightly
	sudo dnf install wezterm
