#!/usr/bin/env bash

sudo apt install -y zsh

echo "Installing oh-my-zsh..."
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended --keep-zshrc

# Clone Zsh plugins
echo "Cloning Zsh plugins..."
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

echo "Zsh configured successfully."

# Install Starship prompt and use Nerd Font symbols
curl -sS https://starship.rs/install.sh | sh -s -- -y
if ! grep -qiE "(Microsoft|WSL)" /proc/version; then
	starship preset nerd-font-symbols -o ~/.config/starship.toml
else
	starship preset plain-text-symbols -o ~/.config/starship.toml
fi
